# Site settings
title: Patrick Marsceill
email: patrick.marsceill@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Design at GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patrickmarsceill.com" # the base hostname & protocol for your site
twitter:
  username: pmarsceill

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag
  - jemoji
permalink: pretty
assets:
  # cache: false | directory | default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_prefix_with_cdn: false
  # prefix: "/a"
  # assets:
  #   - "/a/c/main.css"
  sources:
    - _assets/stylesheets
    - _assets/images
    - _assets/videos
    - _assets/javascripts
  baseurl: http://localhost:4000/assets/
  debug: false
  version: 1
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - Gruntfile.js
  - circle.yml
