###
# Configuration file
# Contains site data, core jekyll config, plugin config, etc.

## Org settings
title: Patrick Marsceill
logo: /assets/img/global/logo.svg
email: patrick.marsceill@gmail.com
city: Philadelphia
state: PA
zip: 19125

microblog_url: 'https://micro.blog/pmarsceill'
twitter_url: 'https://twitter.com/pmarsceill'
github_url: 'https://github.com/pmarsceill'
instagram_url: 'https://instagram.com/pmarsceill'
dribbble_url: 'https://dribbble.com/pmarsceill'
keybase_url: 'https://keybase.io/pmarsceill'

## Site Description
# used in meta tags
description: >
  Patrick Marsceill is a multi-disciplinary designer managing product design at GitHub.

## Analytics
# used to track visitor usage
google_site_tag: true # google's modern tracker code
google_analytics: UA-2709176-3 # UA—XXXXXXXX-X

## Core Site Settings
# jekyll configuration
url: 'https://patrickmarsceill.com'
permalink: /:year/:month/:day/:title/
assets-base-url: '/assets/'
source: src
destination: dist
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: ['dev']
# modules
include: ['_pages', '_data']
exclude: ['assets', 'js', 'sass', 'node_modules', Gemfile, Gemfile.lock, notes.txt, package.json, README.md, 'bower.json']
keep_files:
  - assets
markdown: kramdown
gems:
  - jekyll-seo-tag

# SEO Specific Settings
twitter:
  username: pmarsceill
  domain: patrickmarsceill.com
facebook:
  app_id:
social:
  name: Patrick Marsceill
  links:
    - https://patrickmarsceill.com
    - https://twitter.com/pmarsceill
    - https://keybase.io/pmarsceill
    - https://github.com/pmarsceill
    - https://dribbble.com/pmarsceill
    - https://linkedin.com/pmarsceill
