#!/bin/sh
echo "Compiling site... \n"
bundle exec jekyll build JEKYLL_ENV=production

echo "Running stats on CSS... \n"
grunt parker

echo "Testing SCSS...\n"
stylelint _assets/**/*.scss -c .stylelintrc.json -s scss

echo "\nTesting HTML...\n"
bundle exec htmlproofer ./_site --check-opengraph true --check-html true --http-status-ignore "408,301,0" --url-ignore "/patrickmarsceill.com/" --empty-alt-ignore true
